name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: nightly
          arguments: assembleDebug

      - name: Upload debug apks
        uses: actions/upload-artifact@v4
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/Reef-debug.apk
